### ISSUE TITLE
Bubbles not displaying

### ISSUE THREAD

**Issue by benknoble** [BenziAhamed/alfred-battery#1]
After updating to alfred3, I was looking at battery stats and received the following output.

<img width="694" alt="screen shot 2017-01-08 at 10 32 02 am" src="https://cloud.githubusercontent.com/assets/22802209/21750996/d57652ac-d58d-11e6-8117-3b6b8f31b098.png">

I suspect the issue is in this line of the script, but was unable to fix it

```bash
CELLS=$(python -c "f='●'*($CHARGE/10) + '○'*(10-$CHARGE/10);print f")
```

**Comment by benknoble** [comment]
Terminal output makes me suspect it's an alfred encoding problem

```bash
494 Knoble:~ $ CHARGE=50
495 Knoble:~ $ python -c "f='●'*($CHARGE/10) + '○'*(10-$CHARGE/10);print f"
●●●●●○○○○○
```

**Comment by BenziAhamed** [comment]
Which MacOS version do you have?

**Comment by benknoble** [comment]
OS X El Capitan (10.11.6)

**Comment by benknoble** [comment]
Not sure why, but downloading the workflow from the ReadMe link and updating it in Alfred seemed to do the trick. @BenziAhamed you can close #1
