### ISSUE TITLE
Repository refactoring

### ISSUE THREAD

**Issue by xilopaint** [BenziAhamed/alfred-battery#8]
Hi Benzi!

Would it be possible to refactor this repo with a `/src` directory with the content of the `.alfredworkflow` file? It would make the repo much better for contributions.

Besides that you can distribute the workflow binary via GitHub releases. [Here's](https://github.com/xilopaint/alfred-things) a repo structure for an Alfred workflow.

If you agree with this I can submit a PR with a patch to a bug with the battery health information and some code improvements.

**Comment by BenziAhamed** [comment]
Sure, I think that would be a great idea! 

Please raise a PR and I can merge it.
